apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  labels:
    name: postgres-deploy
    app: vote-example
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-pod
      app: vote-example
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: vote-example
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"