apiVersion: v1
kind: Pod
metadata:
  name: vote-app-pod
  labels:
    name: vote-app-pod
    app: vote-example
spec:
  containers:
    - name: vote-app
      image: kodekloud/examplevotingapp_vote:v1
      ports:
        - containerPort: 80