apiVersion: v1
kind: Service
metadata:
  name: vote-app-service
  labels:
    name: vote-app-service
    app: vote-example
spec:
  type: LoadBalancer 
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
  selector:
    name: vote-app-pod
    app: vote-example
