apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-app-deploy
  labels:
    name: vote-app-deploy
    app: vote-example
spec:
  replicas: 1
  selector:
    matchLabels:
      name: vote-app-pod
      app: vote-example
  template:
    metadata:
      name: vote-app-pod
      labels:
        name: vote-app-pod
        app: vote-example
    spec:
      containers:
        - name: vote-app
          image: kodekloud/examplevotingapp_vote:v1
          ports:
            - containerPort: 80
    