apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    name: worker-app-pod
    app: vote-example
spec:
  containers:
    - name: worker-app
      image: kodekloud/examplevotingapp_worker:v1